# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bbbd23c8914933ba47d391d898a4f1dc75f283876c979c96dec7de5bbd7d818a9ef3e004555f6a222fea1c3a1fad00e9ad025b7d474d3ef1dd04a823a4152d3e

test:
  secret_key_base: 27564d24fa49569ce408b20816975a498b2521c944e1a27a815adbcb68149231ef7427585dac861fd8064dc2cee9a4647844676c028a25ca156ff86599d47b91

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
